import AdminLayout from "../layouts/Admin/AdminLayout";

import {
    Dashboard,
    ExamsList,
    ExamCreateForm,
    ExamUpdateForm,
    ExamDetailsForm,
    ExamTypesList,
    ExamTypeCreateForm,
    ExamTypeUpdateForm,
    ExamTypeDetailsForm,
    FacultiesList,
    FacultyCreateForm,
    FacultyUpdateForm,
    FacultyDetailsForm,
    GroupsList,
    GroupCreateForm,
    GroupUpdateForm,
    GroupDetailsForm,
    GroupSubjectsList,
    GroupSubjectCreateForm,
    GroupSubjectUpdateForm,
    GroupSubjectDetailsForm,
    StudentsList,
    StudentCreateForm,
    StudentUpdateForm,
    StudentDetailsForm,
    SubjectsList,
    SubjectCreateForm,
    SubjectUpdateForm,
    SubjectDetailsForm,
    LessonTypesList,
    LessonTypeCreateForm,
    LessonTypeUpdateForm,
    LessonTypeDetailsForm,
    TeacherRolesList,
    TeacherRoleCreateForm,
    TeacherRoleUpdateForm,
    TeacherRoleDetailsForm,
    TeachersList,
    TeacherCreateForm,
    TeacherUpdateForm,
    TeacherDetailsForm,
    UsersList,
    UserCreateForm,
    UserUpdateForm,
    UserDetailsForm,
    Error404,
    Error500,
} from '../pages/Admin'


const adminRoutes = [
    {
        path: "/admin",
        element: <AdminLayout />,
        errorElement: <Error404 />,
        children: [
            { path: "", element: <Dashboard />, label: "Dashboard" },
            // { path: "Exams", element: <ExamsList />, label: "Exams" },
            // { path: "Exams/CreateExam", element: <ExamCreateForm />, label: "ExamsCreate" },
            // { path: "Exams/UpdateExam/:Id", element: <ExamUpdateForm />, label: "ExamsUpdate" },
            // { path: "Exams/:Id", element: <ExamDetailsForm />, label: "ExamsDetails" },

            { path: "ExamTypes", element: <ExamTypesList />, label: "ExamTypes" },
            { path: "ExamTypes/CreateExamType", element: <ExamTypeCreateForm />, label: "ExamTypesCreate" },
            { path: "ExamTypes/UpdateExamType/:examTypeId", element: <ExamTypeUpdateForm />, label: "ExamTypesUpdate" },
            // { path: "ExamTypes/:examTypeId", element: <ExamTypeDetailsForm />, label: "ExamTypesDetails" },

            { path: "Faculties", element: <FacultiesList />, label: "Faculties" },
            { path: "Faculties/CreateFaculty", element: <FacultyCreateForm />, label: "FacultiesCreate" },
            { path: "Faculties/UpdateFaculty/:facultyId", element: <FacultyUpdateForm />, label: "FacultiesUpdate" },
            { path: "Faculties/:facultyId", element: <FacultyDetailsForm />, label: "FacultiesDetails" },
            // { path: "Groups", element: <GroupsList />, label: "Groups" },
            // { path: "Groups/CreateGroup", element: <GroupCreateForm />, label: "GroupsCreate" },
            // { path: "Groups/UpdateGroup/:Id", element: <GroupUpdateForm />, label: "GroupsUpdate" },
            // { path: "Groups/:Id", element: <GroupDetailsForm />, label: "GroupsDetails" },
            { path: "GroupSubjects", element: <GroupSubjectsList />, label: "GroupSubjects" },
            { path: "GroupSubjects/CreateGroupSubject", element: <GroupSubjectCreateForm />, label: "GroupSubjectsCreate" },
            { path: "GroupSubjects/UpdateGroupSubject/:groupSubjectId", element: <GroupSubjectUpdateForm />, label: "GroupSubjectsUpdate" },
            { path: "GroupSubjects/:groupSubjectId", element: <GroupSubjectDetailsForm />, label: "GroupSubjectsDetails" },
            { path: "Students", element: <StudentsList />, label: "Students" },
            { path: "Students/CreateStudent", element: <StudentCreateForm />, label: "StudentsCreate" },
            { path: "Students/UpdateStudent/:studentId", element: <StudentUpdateForm />, label: "StudentsUpdate" },
            { path: "Students/:studentId", element: <StudentDetailsForm />, label: "StudentsDetails" },

            { path: "Subjects", element: <SubjectsList />, label: "Subjects" },
            { path: "Subjects/CreateGroup", element: <SubjectCreateForm />, label: "SubjectsCreate" },
            { path: "Subjects/UpdateGroup/:subjectId", element: <SubjectUpdateForm />, label: "SubjectsUpdate" },
            { path: "Subjects/:subjectId", element: <SubjectDetailsForm />, label: "SubjectsDetails" },

            { path: "LessonTypes", element: <LessonTypesList />, label: "LessonTypes" },
            { path: "LessonTypes/CreateLessonType", element: <LessonTypeCreateForm />, label: "LessonTypesCreate" },
            { path: "LessonTypes/UpdateLessonType/:lessonTypeId", element: <LessonTypeUpdateForm />, label: "LessonTypesUpdate" },
            // { path: "LessonTypes/:lessonTypeId", element: <LessonTypeDetailsForm />, label: "LessonTypesDetails" },

            { path: "TeacherRoles", element: <TeacherRolesList />, label: "TeacherRoles" },
            { path: "TeacherRoles/CreateTeacherRole", element: <TeacherRoleCreateForm />, label: "TeacherRolesCreate" },
            { path: "TeacherRoles/UpdateTeacherRole/:teacherRoleId", element: <TeacherRoleUpdateForm />, label: "TeacherRolesUpdate" },
            // { path: "TeacherRoles/:teacherRoleId", element: <TeacherRoleDetailsForm />, label: "TeacherRolesDetails" },
            { path: "Teachers", element: <TeachersList />, label: "Teachers" },
            { path: "Teachers/CreateTeacher", element: <TeacherCreateForm />, label: "TeachersCreate" },
            { path: "Teachers/UpdateTeacher/:teacherId", element: <TeacherUpdateForm />, label: "TeachersUpdate" },
            // { path: "Teachers/:TeacherId", element: <TeacherDetailsForm />, label: "TeachersDetails" },
            { path: "Users", element: <UsersList />, label: "Users" },
            { path: "Users/CreateUser", element: <UserCreateForm />, label: "UsersCreate" },
            { path: "Users/UpdateUser/:userId", element: <UserUpdateForm />, label: "UsersUpdate" },
            { path: "Users/:userId", element: <UserDetailsForm />, label: "UsersDetails" },

            // { path: "Users/CreateUser", element: <SignUp />, label: "UsersCreate" },
        ]
    },
    { path: "error500", element: <Error500 /> },
];

export default adminRoutes;