// Event Statuses
export const EVENT_STATUSES = [
    "Draft",
    "Scheduled",
    "Confirmed",
    "Ongoing",
    "Completed",
    "Cancelled",
    "Postponed",
    "Rescheduled",
    "SoldOut",
    "Archived",
  ];
  
  // Ticket Types
  export const EDUCATION_STATUSES = ["Studies", "Graduated"];

  export const GENDERS = ["Male", "Female", "Email"];
  
  export const SUB_GROUPS = ["Normal", "LowerGroup", "UpperGroup"];

  export const TEACHER_ROLES = ["Seminar", "Lecture", "Laboratory"];

  export const EXAM_TYPES = ["Colloquim", "Final"];

  export const LESSON_TYPES = ["Seminar", "Lecture", "Laboratory"];

  export const SEMESTERS = ["Autumn1", "Spring1", "Autumn2", "Spring2", "Autumn3", "Spring3", "Autumn4", "Spring4"];
  
  // Ticket Statuses
  export const COUNTRIES = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "AntiguaAndBarbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "BosniaAndHerzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "BurkinaFaso",
    "Burundi",
    "CaboVerde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "CentralAfricanRepublic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "CostaRica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "CzechRepublic",
    "DemocraticRepublicOfTheCongo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "DominicanRepublic",
    "EastTimor",
    "Ecuador",
    "Egypt",
    "ElSalvador",
    "EquatorialGuinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "GuineaBissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "IvoryCoast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "MarshallIslands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "NewZealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "NorthKorea",
    "NorthMacedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "PapuaNewGuinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "SaintKittsAndNevis",
    "SaintLucia",
    "SaintVincentAndTheGrenadines",
    "Samoa",
    "SanMarino",
    "SaoTomeAndPrincipe",
    "SaudiArabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "SierraLeone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "SolomonIslands",
    "Somalia",
    "SouthAfrica",
    "SouthKorea",
    "SouthSudan",
    "Spain",
    "SriLanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "TrinidadAndTobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "UnitedArabEmirates",
    "UnitedKingdom",
    "UnitedStates",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "VaticanCity",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ];
  

//   // Ticket Statuses
//   export const TICKET_STATUSES = [
//       "Available",
//       "Sold", 
//       "Used", 
//       "Expired", 
//       "Cancelled"
//   ]